### ISSUE TITLE
seafile:// specification?

### ISSUE THREAD

**Issue by picrap** [carlos22/seafile-protocol-xdg#2]
Hi, do you have any documentation regarding the URI format itself? In other words, what does this URI allow to link? And how?

**Comment by carlos22** [comment]
No Spec but the webapp generates such links. Its bascially the ID of the repo plus the path to the file. 

For example:
```
seafile://openfile?repo_id=b3159e02-67c1-4888-a455-3cdxzy2e3c8&path=%2FPath%2FsomeFile.txt
```

The applet (app) on the desktop uses this protocol and opens the file (or folder). But it only registers handlers for it on windows (and maybe mac) but not linux thats why i came up with this.

**Comment by picrap** [comment]
That’s a start. Thank you.
